#############################################################################
# Makefile for building: DiabloEdit
# Generated by qmake (3.1) (Qt 5.15.19)
# Project:  DiabloEdit.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile DiabloEdit.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++1z -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -Isrc -Isrc/core -Isrc/data -Isrc/ui -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I. -I/usr/lib/qt/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = DiabloEdit1.0.0
DISTDIR = /home/zl/code/diablo_edit/.tmp/DiabloEdit1.0.0
LINK          = g++
LFLAGS        = -fPIC
LIBS          = $(SUBLIBS) /usr/lib/libQt5Widgets.so /usr/lib/libQt5Gui.so /usr/lib/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/core/BinDataStream.cpp \
		src/core/MetaData.cpp \
		src/core/D2Item.cpp \
		src/core/D2S_Struct.cpp \
		src/core/ImageManager.cpp \
		src/core/quicklz.cpp \
		src/data/DataManager.cpp \
		src/ui/MainWindow.cpp \
		src/ui/CharInfoWidget.cpp \
		src/ui/WaypointsWidget.cpp \
		src/ui/QuestInfoWidget.cpp \
		src/ui/SkillsDialog.cpp \
		src/ui/SelectCharDialog.cpp \
		src/ui/ItemTooltip.cpp \
		src/ui/ItemGridWidget.cpp \
		src/ui/NewItemDialog.cpp \
		src/ui/FoundryDialog.cpp \
		src/main.cpp qrc_resources.cpp \
		moc_ImageManager.cpp \
		moc_MainWindow.cpp \
		moc_CharInfoWidget.cpp \
		moc_WaypointsWidget.cpp \
		moc_QuestInfoWidget.cpp \
		moc_SkillsDialog.cpp \
		moc_SelectCharDialog.cpp \
		moc_ItemTooltip.cpp \
		moc_ItemGridWidget.cpp \
		moc_NewItemDialog.cpp \
		moc_FoundryDialog.cpp
OBJECTS       = BinDataStream.o \
		MetaData.o \
		D2Item.o \
		D2S_Struct.o \
		ImageManager.o \
		quicklz.o \
		DataManager.o \
		MainWindow.o \
		CharInfoWidget.o \
		WaypointsWidget.o \
		QuestInfoWidget.o \
		SkillsDialog.o \
		SelectCharDialog.o \
		ItemTooltip.o \
		ItemGridWidget.o \
		NewItemDialog.o \
		FoundryDialog.o \
		main.o \
		qrc_resources.o \
		moc_ImageManager.o \
		moc_MainWindow.o \
		moc_CharInfoWidget.o \
		moc_WaypointsWidget.o \
		moc_QuestInfoWidget.o \
		moc_SkillsDialog.o \
		moc_SelectCharDialog.o \
		moc_ItemTooltip.o \
		moc_ItemGridWidget.o \
		moc_NewItemDialog.o \
		moc_FoundryDialog.o
DIST          = /usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/sanitize.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/toolchain.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/ltcg.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/resources_functions.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/link_ltcg.prf \
		/usr/lib/qt/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt/mkspecs/features/uic.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/qmake_use.prf \
		/usr/lib/qt/mkspecs/features/file_copies.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		DiabloEdit.pro src/core/D2Types.h \
		src/core/D2Version.h \
		src/core/BinDataStream.h \
		src/core/MayExist.h \
		src/core/MetaData.h \
		src/core/DataManagerFwd.h \
		src/core/D2Item.h \
		src/core/D2S_Struct.h \
		src/core/ImageManager.h \
		src/core/quicklz.h \
		src/core/compress_quicklz.h \
		src/data/DataManager.h \
		src/ui/MainWindow.h \
		src/ui/CharInfoWidget.h \
		src/ui/WaypointsWidget.h \
		src/ui/QuestInfoWidget.h \
		src/ui/SkillsDialog.h \
		src/ui/SelectCharDialog.h \
		src/ui/ItemTooltip.h \
		src/ui/ItemGridWidget.h \
		src/ui/NewItemDialog.h \
		src/ui/FoundryDialog.h src/core/BinDataStream.cpp \
		src/core/MetaData.cpp \
		src/core/D2Item.cpp \
		src/core/D2S_Struct.cpp \
		src/core/ImageManager.cpp \
		src/core/quicklz.cpp \
		src/data/DataManager.cpp \
		src/ui/MainWindow.cpp \
		src/ui/CharInfoWidget.cpp \
		src/ui/WaypointsWidget.cpp \
		src/ui/QuestInfoWidget.cpp \
		src/ui/SkillsDialog.cpp \
		src/ui/SelectCharDialog.cpp \
		src/ui/ItemTooltip.cpp \
		src/ui/ItemGridWidget.cpp \
		src/ui/NewItemDialog.cpp \
		src/ui/FoundryDialog.cpp \
		src/main.cpp
QMAKE_TARGET  = DiabloEdit
DESTDIR       = 
TARGET        = DiabloEdit


first: all
####### Build rules

DiabloEdit:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: DiabloEdit.pro /usr/lib/qt/mkspecs/linux-g++/qmake.conf /usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/sanitize.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/toolchain.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/ltcg.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/resources_functions.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/link_ltcg.prf \
		/usr/lib/qt/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt/mkspecs/features/uic.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/qmake_use.prf \
		/usr/lib/qt/mkspecs/features/file_copies.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		DiabloEdit.pro \
		resources/resources.qrc
	$(QMAKE) -o Makefile DiabloEdit.pro
/usr/lib/qt/mkspecs/features/spec_pre.prf:
/usr/lib/qt/mkspecs/common/unix.conf:
/usr/lib/qt/mkspecs/common/linux.conf:
/usr/lib/qt/mkspecs/common/sanitize.conf:
/usr/lib/qt/mkspecs/common/gcc-base.conf:
/usr/lib/qt/mkspecs/common/gcc-base-unix.conf:
/usr/lib/qt/mkspecs/common/g++-base.conf:
/usr/lib/qt/mkspecs/common/g++-unix.conf:
/usr/lib/qt/mkspecs/qconfig.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/qt/mkspecs/features/qt_functions.prf:
/usr/lib/qt/mkspecs/features/qt_config.prf:
/usr/lib/qt/mkspecs/linux-g++/qmake.conf:
/usr/lib/qt/mkspecs/features/spec_post.prf:
/usr/lib/qt/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt/mkspecs/features/toolchain.prf:
/usr/lib/qt/mkspecs/features/default_pre.prf:
/usr/lib/qt/mkspecs/features/resolve_config.prf:
/usr/lib/qt/mkspecs/features/default_post.prf:
/usr/lib/qt/mkspecs/features/ltcg.prf:
/usr/lib/qt/mkspecs/features/warn_on.prf:
/usr/lib/qt/mkspecs/features/qt.prf:
/usr/lib/qt/mkspecs/features/resources_functions.prf:
/usr/lib/qt/mkspecs/features/resources.prf:
/usr/lib/qt/mkspecs/features/moc.prf:
/usr/lib/qt/mkspecs/features/link_ltcg.prf:
/usr/lib/qt/mkspecs/features/unix/opengl.prf:
/usr/lib/qt/mkspecs/features/uic.prf:
/usr/lib/qt/mkspecs/features/unix/thread.prf:
/usr/lib/qt/mkspecs/features/qmake_use.prf:
/usr/lib/qt/mkspecs/features/file_copies.prf:
/usr/lib/qt/mkspecs/features/testcase_targets.prf:
/usr/lib/qt/mkspecs/features/exceptions.prf:
/usr/lib/qt/mkspecs/features/yacc.prf:
/usr/lib/qt/mkspecs/features/lex.prf:
DiabloEdit.pro:
resources/resources.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile DiabloEdit.pro

qmake_all: FORCE


all: Makefile DiabloEdit

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources/resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/qt/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/core/D2Types.h src/core/D2Version.h src/core/BinDataStream.h src/core/MayExist.h src/core/MetaData.h src/core/DataManagerFwd.h src/core/D2Item.h src/core/D2S_Struct.h src/core/ImageManager.h src/core/quicklz.h src/core/compress_quicklz.h src/data/DataManager.h src/ui/MainWindow.h src/ui/CharInfoWidget.h src/ui/WaypointsWidget.h src/ui/QuestInfoWidget.h src/ui/SkillsDialog.h src/ui/SelectCharDialog.h src/ui/ItemTooltip.h src/ui/ItemGridWidget.h src/ui/NewItemDialog.h src/ui/FoundryDialog.h $(DISTDIR)/
	$(COPY_FILE) --parents src/core/BinDataStream.cpp src/core/MetaData.cpp src/core/D2Item.cpp src/core/D2S_Struct.cpp src/core/ImageManager.cpp src/core/quicklz.cpp src/data/DataManager.cpp src/ui/MainWindow.cpp src/ui/CharInfoWidget.cpp src/ui/WaypointsWidget.cpp src/ui/QuestInfoWidget.cpp src/ui/SkillsDialog.cpp src/ui/SelectCharDialog.cpp src/ui/ItemTooltip.cpp src/ui/ItemGridWidget.cpp src/ui/NewItemDialog.cpp src/ui/FoundryDialog.cpp src/main.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources/resources.qrc \
		/usr/bin/rcc
	/usr/bin/rcc -name resources resources/resources.qrc -o qrc_resources.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/qt/mkspecs/features/data/dummy.cpp
	g++ -pipe -g -std=gnu++1z -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/qt/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_ImageManager.cpp moc_MainWindow.cpp moc_CharInfoWidget.cpp moc_WaypointsWidget.cpp moc_QuestInfoWidget.cpp moc_SkillsDialog.cpp moc_SelectCharDialog.cpp moc_ItemTooltip.cpp moc_ItemGridWidget.cpp moc_NewItemDialog.cpp moc_FoundryDialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_ImageManager.cpp moc_MainWindow.cpp moc_CharInfoWidget.cpp moc_WaypointsWidget.cpp moc_QuestInfoWidget.cpp moc_SkillsDialog.cpp moc_SelectCharDialog.cpp moc_ItemTooltip.cpp moc_ItemGridWidget.cpp moc_NewItemDialog.cpp moc_FoundryDialog.cpp
moc_ImageManager.cpp: src/core/ImageManager.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/zl/code/diablo_edit/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/zl/code/diablo_edit -I/home/zl/code/diablo_edit/src -I/home/zl/code/diablo_edit/src/core -I/home/zl/code/diablo_edit/src/data -I/home/zl/code/diablo_edit/src/ui -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/16.1.1 -I/usr/include/c++/16.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/16.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/16.1.1/include -I/usr/local/include -I/usr/include src/core/ImageManager.h -o moc_ImageManager.cpp

moc_MainWindow.cpp: src/ui/MainWindow.h \
		src/core/D2S_Struct.h \
		src/core/D2Item.h \
		src/core/MetaData.h \
		src/core/D2Types.h \
		src/core/MayExist.h \
		src/core/BinDataStream.h \
		src/core/D2Version.h \
		src/core/DataManagerFwd.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/zl/code/diablo_edit/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/zl/code/diablo_edit -I/home/zl/code/diablo_edit/src -I/home/zl/code/diablo_edit/src/core -I/home/zl/code/diablo_edit/src/data -I/home/zl/code/diablo_edit/src/ui -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/16.1.1 -I/usr/include/c++/16.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/16.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/16.1.1/include -I/usr/local/include -I/usr/include src/ui/MainWindow.h -o moc_MainWindow.cpp

moc_CharInfoWidget.cpp: src/ui/CharInfoWidget.h \
		src/core/D2S_Struct.h \
		src/core/D2Item.h \
		src/core/MetaData.h \
		src/core/D2Types.h \
		src/core/MayExist.h \
		src/core/BinDataStream.h \
		src/core/D2Version.h \
		src/core/DataManagerFwd.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/zl/code/diablo_edit/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/zl/code/diablo_edit -I/home/zl/code/diablo_edit/src -I/home/zl/code/diablo_edit/src/core -I/home/zl/code/diablo_edit/src/data -I/home/zl/code/diablo_edit/src/ui -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/16.1.1 -I/usr/include/c++/16.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/16.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/16.1.1/include -I/usr/local/include -I/usr/include src/ui/CharInfoWidget.h -o moc_CharInfoWidget.cpp

moc_WaypointsWidget.cpp: src/ui/WaypointsWidget.h \
		src/core/D2S_Struct.h \
		src/core/D2Item.h \
		src/core/MetaData.h \
		src/core/D2Types.h \
		src/core/MayExist.h \
		src/core/BinDataStream.h \
		src/core/D2Version.h \
		src/core/DataManagerFwd.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/zl/code/diablo_edit/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/zl/code/diablo_edit -I/home/zl/code/diablo_edit/src -I/home/zl/code/diablo_edit/src/core -I/home/zl/code/diablo_edit/src/data -I/home/zl/code/diablo_edit/src/ui -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/16.1.1 -I/usr/include/c++/16.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/16.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/16.1.1/include -I/usr/local/include -I/usr/include src/ui/WaypointsWidget.h -o moc_WaypointsWidget.cpp

moc_QuestInfoWidget.cpp: src/ui/QuestInfoWidget.h \
		src/core/D2S_Struct.h \
		src/core/D2Item.h \
		src/core/MetaData.h \
		src/core/D2Types.h \
		src/core/MayExist.h \
		src/core/BinDataStream.h \
		src/core/D2Version.h \
		src/core/DataManagerFwd.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/zl/code/diablo_edit/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/zl/code/diablo_edit -I/home/zl/code/diablo_edit/src -I/home/zl/code/diablo_edit/src/core -I/home/zl/code/diablo_edit/src/data -I/home/zl/code/diablo_edit/src/ui -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/16.1.1 -I/usr/include/c++/16.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/16.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/16.1.1/include -I/usr/local/include -I/usr/include src/ui/QuestInfoWidget.h -o moc_QuestInfoWidget.cpp

moc_SkillsDialog.cpp: src/ui/SkillsDialog.h \
		src/core/D2Types.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/zl/code/diablo_edit/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/zl/code/diablo_edit -I/home/zl/code/diablo_edit/src -I/home/zl/code/diablo_edit/src/core -I/home/zl/code/diablo_edit/src/data -I/home/zl/code/diablo_edit/src/ui -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/16.1.1 -I/usr/include/c++/16.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/16.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/16.1.1/include -I/usr/local/include -I/usr/include src/ui/SkillsDialog.h -o moc_SkillsDialog.cpp

moc_SelectCharDialog.cpp: src/ui/SelectCharDialog.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/zl/code/diablo_edit/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/zl/code/diablo_edit -I/home/zl/code/diablo_edit/src -I/home/zl/code/diablo_edit/src/core -I/home/zl/code/diablo_edit/src/data -I/home/zl/code/diablo_edit/src/ui -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/16.1.1 -I/usr/include/c++/16.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/16.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/16.1.1/include -I/usr/local/include -I/usr/include src/ui/SelectCharDialog.h -o moc_SelectCharDialog.cpp

moc_ItemTooltip.cpp: src/ui/ItemTooltip.h \
		src/core/D2Item.h \
		src/core/MetaData.h \
		src/core/D2Types.h \
		src/core/MayExist.h \
		src/core/BinDataStream.h \
		src/core/D2Version.h \
		src/core/DataManagerFwd.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/zl/code/diablo_edit/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/zl/code/diablo_edit -I/home/zl/code/diablo_edit/src -I/home/zl/code/diablo_edit/src/core -I/home/zl/code/diablo_edit/src/data -I/home/zl/code/diablo_edit/src/ui -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/16.1.1 -I/usr/include/c++/16.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/16.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/16.1.1/include -I/usr/local/include -I/usr/include src/ui/ItemTooltip.h -o moc_ItemTooltip.cpp

moc_ItemGridWidget.cpp: src/ui/ItemGridWidget.h \
		src/core/D2S_Struct.h \
		src/core/D2Item.h \
		src/core/MetaData.h \
		src/core/D2Types.h \
		src/core/MayExist.h \
		src/core/BinDataStream.h \
		src/core/D2Version.h \
		src/core/DataManagerFwd.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/zl/code/diablo_edit/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/zl/code/diablo_edit -I/home/zl/code/diablo_edit/src -I/home/zl/code/diablo_edit/src/core -I/home/zl/code/diablo_edit/src/data -I/home/zl/code/diablo_edit/src/ui -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/16.1.1 -I/usr/include/c++/16.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/16.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/16.1.1/include -I/usr/local/include -I/usr/include src/ui/ItemGridWidget.h -o moc_ItemGridWidget.cpp

moc_NewItemDialog.cpp: src/ui/NewItemDialog.h \
		src/core/D2Item.h \
		src/core/MetaData.h \
		src/core/D2Types.h \
		src/core/MayExist.h \
		src/core/BinDataStream.h \
		src/core/D2Version.h \
		src/core/DataManagerFwd.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/zl/code/diablo_edit/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/zl/code/diablo_edit -I/home/zl/code/diablo_edit/src -I/home/zl/code/diablo_edit/src/core -I/home/zl/code/diablo_edit/src/data -I/home/zl/code/diablo_edit/src/ui -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/16.1.1 -I/usr/include/c++/16.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/16.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/16.1.1/include -I/usr/local/include -I/usr/include src/ui/NewItemDialog.h -o moc_NewItemDialog.cpp

moc_FoundryDialog.cpp: src/ui/FoundryDialog.h \
		src/core/D2Item.h \
		src/core/MetaData.h \
		src/core/D2Types.h \
		src/core/MayExist.h \
		src/core/BinDataStream.h \
		src/core/D2Version.h \
		src/core/DataManagerFwd.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/zl/code/diablo_edit/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/zl/code/diablo_edit -I/home/zl/code/diablo_edit/src -I/home/zl/code/diablo_edit/src/core -I/home/zl/code/diablo_edit/src/data -I/home/zl/code/diablo_edit/src/ui -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/16.1.1 -I/usr/include/c++/16.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/16.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/16.1.1/include -I/usr/local/include -I/usr/include src/ui/FoundryDialog.h -o moc_FoundryDialog.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

BinDataStream.o: src/core/BinDataStream.cpp src/core/BinDataStream.h \
		src/core/D2Types.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BinDataStream.o src/core/BinDataStream.cpp

MetaData.o: src/core/MetaData.cpp src/core/MetaData.h \
		src/core/D2Types.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MetaData.o src/core/MetaData.cpp

D2Item.o: src/core/D2Item.cpp src/core/D2Item.h \
		src/core/MetaData.h \
		src/core/D2Types.h \
		src/core/MayExist.h \
		src/core/BinDataStream.h \
		src/core/D2Version.h \
		src/core/DataManagerFwd.h \
		src/data/DataManager.h \
		src/core/D2S_Struct.h \
		src/core/compress_quicklz.h \
		src/core/quicklz.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o D2Item.o src/core/D2Item.cpp

D2S_Struct.o: src/core/D2S_Struct.cpp src/core/D2S_Struct.h \
		src/core/D2Item.h \
		src/core/MetaData.h \
		src/core/D2Types.h \
		src/core/MayExist.h \
		src/core/BinDataStream.h \
		src/core/D2Version.h \
		src/core/DataManagerFwd.h \
		src/data/DataManager.h \
		src/core/compress_quicklz.h \
		src/core/quicklz.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o D2S_Struct.o src/core/D2S_Struct.cpp

ImageManager.o: src/core/ImageManager.cpp src/core/ImageManager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ImageManager.o src/core/ImageManager.cpp

quicklz.o: src/core/quicklz.cpp src/core/quicklz.c.h \
		src/core/quicklz.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o quicklz.o src/core/quicklz.cpp

DataManager.o: src/data/DataManager.cpp src/data/DataManager.h \
		src/core/D2Types.h \
		src/core/MetaData.h \
		src/core/D2S_Struct.h \
		src/core/D2Item.h \
		src/core/MayExist.h \
		src/core/BinDataStream.h \
		src/core/D2Version.h \
		src/core/DataManagerFwd.h \
		src/core/compress_quicklz.h \
		src/core/quicklz.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DataManager.o src/data/DataManager.cpp

MainWindow.o: src/ui/MainWindow.cpp src/ui/MainWindow.h \
		src/core/D2S_Struct.h \
		src/core/D2Item.h \
		src/core/MetaData.h \
		src/core/D2Types.h \
		src/core/MayExist.h \
		src/core/BinDataStream.h \
		src/core/D2Version.h \
		src/core/DataManagerFwd.h \
		src/ui/CharInfoWidget.h \
		src/ui/ItemGridWidget.h \
		src/ui/SkillsDialog.h \
		src/ui/SelectCharDialog.h \
		src/ui/FoundryDialog.h \
		src/ui/NewItemDialog.h \
		src/core/ImageManager.h \
		src/data/DataManager.h \
		src/core/compress_quicklz.h \
		src/core/quicklz.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainWindow.o src/ui/MainWindow.cpp

CharInfoWidget.o: src/ui/CharInfoWidget.cpp src/ui/CharInfoWidget.h \
		src/core/D2S_Struct.h \
		src/core/D2Item.h \
		src/core/MetaData.h \
		src/core/D2Types.h \
		src/core/MayExist.h \
		src/core/BinDataStream.h \
		src/core/D2Version.h \
		src/core/DataManagerFwd.h \
		src/ui/WaypointsWidget.h \
		src/ui/QuestInfoWidget.h \
		src/data/DataManager.h \
		src/core/compress_quicklz.h \
		src/core/quicklz.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CharInfoWidget.o src/ui/CharInfoWidget.cpp

WaypointsWidget.o: src/ui/WaypointsWidget.cpp src/ui/WaypointsWidget.h \
		src/core/D2S_Struct.h \
		src/core/D2Item.h \
		src/core/MetaData.h \
		src/core/D2Types.h \
		src/core/MayExist.h \
		src/core/BinDataStream.h \
		src/core/D2Version.h \
		src/core/DataManagerFwd.h \
		src/data/DataManager.h \
		src/core/compress_quicklz.h \
		src/core/quicklz.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o WaypointsWidget.o src/ui/WaypointsWidget.cpp

QuestInfoWidget.o: src/ui/QuestInfoWidget.cpp src/ui/QuestInfoWidget.h \
		src/core/D2S_Struct.h \
		src/core/D2Item.h \
		src/core/MetaData.h \
		src/core/D2Types.h \
		src/core/MayExist.h \
		src/core/BinDataStream.h \
		src/core/D2Version.h \
		src/core/DataManagerFwd.h \
		src/data/DataManager.h \
		src/core/compress_quicklz.h \
		src/core/quicklz.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QuestInfoWidget.o src/ui/QuestInfoWidget.cpp

SkillsDialog.o: src/ui/SkillsDialog.cpp src/ui/SkillsDialog.h \
		src/core/D2Types.h \
		src/data/DataManager.h \
		src/core/MetaData.h \
		src/core/D2S_Struct.h \
		src/core/D2Item.h \
		src/core/MayExist.h \
		src/core/BinDataStream.h \
		src/core/D2Version.h \
		src/core/DataManagerFwd.h \
		src/core/compress_quicklz.h \
		src/core/quicklz.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SkillsDialog.o src/ui/SkillsDialog.cpp

SelectCharDialog.o: src/ui/SelectCharDialog.cpp src/ui/SelectCharDialog.h \
		src/data/DataManager.h \
		src/core/D2Types.h \
		src/core/MetaData.h \
		src/core/D2S_Struct.h \
		src/core/D2Item.h \
		src/core/MayExist.h \
		src/core/BinDataStream.h \
		src/core/D2Version.h \
		src/core/DataManagerFwd.h \
		src/core/compress_quicklz.h \
		src/core/quicklz.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SelectCharDialog.o src/ui/SelectCharDialog.cpp

ItemTooltip.o: src/ui/ItemTooltip.cpp src/ui/ItemTooltip.h \
		src/core/D2Item.h \
		src/core/MetaData.h \
		src/core/D2Types.h \
		src/core/MayExist.h \
		src/core/BinDataStream.h \
		src/core/D2Version.h \
		src/core/DataManagerFwd.h \
		src/data/DataManager.h \
		src/core/D2S_Struct.h \
		src/core/compress_quicklz.h \
		src/core/quicklz.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ItemTooltip.o src/ui/ItemTooltip.cpp

ItemGridWidget.o: src/ui/ItemGridWidget.cpp src/ui/ItemGridWidget.h \
		src/core/D2S_Struct.h \
		src/core/D2Item.h \
		src/core/MetaData.h \
		src/core/D2Types.h \
		src/core/MayExist.h \
		src/core/BinDataStream.h \
		src/core/D2Version.h \
		src/core/DataManagerFwd.h \
		src/ui/ItemTooltip.h \
		src/core/ImageManager.h \
		src/data/DataManager.h \
		src/core/compress_quicklz.h \
		src/core/quicklz.h \
		src/ui/FoundryDialog.h \
		src/ui/NewItemDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ItemGridWidget.o src/ui/ItemGridWidget.cpp

NewItemDialog.o: src/ui/NewItemDialog.cpp src/ui/NewItemDialog.h \
		src/core/D2Item.h \
		src/core/MetaData.h \
		src/core/D2Types.h \
		src/core/MayExist.h \
		src/core/BinDataStream.h \
		src/core/D2Version.h \
		src/core/DataManagerFwd.h \
		src/core/ImageManager.h \
		src/data/DataManager.h \
		src/core/D2S_Struct.h \
		src/core/compress_quicklz.h \
		src/core/quicklz.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o NewItemDialog.o src/ui/NewItemDialog.cpp

FoundryDialog.o: src/ui/FoundryDialog.cpp src/ui/FoundryDialog.h \
		src/core/D2Item.h \
		src/core/MetaData.h \
		src/core/D2Types.h \
		src/core/MayExist.h \
		src/core/BinDataStream.h \
		src/core/D2Version.h \
		src/core/DataManagerFwd.h \
		src/core/ImageManager.h \
		src/data/DataManager.h \
		src/core/D2S_Struct.h \
		src/core/compress_quicklz.h \
		src/core/quicklz.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FoundryDialog.o src/ui/FoundryDialog.cpp

main.o: src/main.cpp src/ui/MainWindow.h \
		src/core/D2S_Struct.h \
		src/core/D2Item.h \
		src/core/MetaData.h \
		src/core/D2Types.h \
		src/core/MayExist.h \
		src/core/BinDataStream.h \
		src/core/D2Version.h \
		src/core/DataManagerFwd.h \
		src/data/DataManager.h \
		src/core/compress_quicklz.h \
		src/core/quicklz.h \
		src/core/ImageManager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_ImageManager.o: moc_ImageManager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ImageManager.o moc_ImageManager.cpp

moc_MainWindow.o: moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainWindow.o moc_MainWindow.cpp

moc_CharInfoWidget.o: moc_CharInfoWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CharInfoWidget.o moc_CharInfoWidget.cpp

moc_WaypointsWidget.o: moc_WaypointsWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_WaypointsWidget.o moc_WaypointsWidget.cpp

moc_QuestInfoWidget.o: moc_QuestInfoWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_QuestInfoWidget.o moc_QuestInfoWidget.cpp

moc_SkillsDialog.o: moc_SkillsDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SkillsDialog.o moc_SkillsDialog.cpp

moc_SelectCharDialog.o: moc_SelectCharDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SelectCharDialog.o moc_SelectCharDialog.cpp

moc_ItemTooltip.o: moc_ItemTooltip.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ItemTooltip.o moc_ItemTooltip.cpp

moc_ItemGridWidget.o: moc_ItemGridWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ItemGridWidget.o moc_ItemGridWidget.cpp

moc_NewItemDialog.o: moc_NewItemDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_NewItemDialog.o moc_NewItemDialog.cpp

moc_FoundryDialog.o: moc_FoundryDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_FoundryDialog.o moc_FoundryDialog.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

